//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCKutuphane.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblhareketler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblhareketler()
        {
            this.tblcezalar = new HashSet<tblcezalar>();
        }
    
        public int ID { get; set; }
        public Nullable<int> KITAP { get; set; }
        public Nullable<int> UYE { get; set; }
        public Nullable<byte> PERSONEL { get; set; }
        public Nullable<System.DateTime> ALISTARIH { get; set; }
        public Nullable<System.DateTime> IADETARIH { get; set; }
        public Nullable<System.DateTime> UYEGETIRTARIH { get; set; }
        public Nullable<bool> ISLEMDURUM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblcezalar> tblcezalar { get; set; }
        public virtual tblkitaplar tblkitaplar { get; set; }
        public virtual tblpersoneller tblpersoneller { get; set; }
        public virtual tbluyeler tbluyeler { get; set; }
    }
}
