//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCKutuphane.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblpersoneller
    {
        public tblpersoneller()
        {
            this.tblhareketler = new HashSet<tblhareketler>();
        }
    

        public byte ID { get; set; }
        //Data Annotations kütüphanesini ekleyerek error mesajlarý alýyoruz. Personel ekle sayfasýnda validation helperini kullandýk.
        [Required(ErrorMessage ="Adý boþ geçemezsiniz") ]
        public string PERSONEL { get; set; }
    
        public virtual ICollection<tblhareketler> tblhareketler { get; set; }
    }
}
