//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCKutuphane.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbluyeler
    {
        public tbluyeler()
        {
            this.tblcezalar = new HashSet<tblcezalar>();
            this.tblhareketler = new HashSet<tblhareketler>();
        }
    
        public int ID { get; set; }
        //Data Annotations kütüphanesini ekleyerek error mesajlarý alýyoruz. Yazar Ekle sayfasýnda validation helperini kullandýk.
        [Required(ErrorMessage ="Adý Boþ býrakamazsýnýz.")]
        [StringLength(20,ErrorMessage ="En fazla 20 karakter girebilirsiniz.")]
        public string AD { get; set; }
        public string SOYAD { get; set; }
        public string MAIL { get; set; }
        public string KULLANICIADI { get; set; }
        [Required(ErrorMessage ="Þifreyi boþ geçemezsiniz.")]
        [StringLength(10,ErrorMessage ="En fazla 10 karakterli bir þifre girin.")]
        public string SIFRE { get; set; }
        public string FOTOGRAF { get; set; }
        public string TELEFON { get; set; }
        public string OKUL { get; set; }
    
        public virtual ICollection<tblcezalar> tblcezalar { get; set; }
        public virtual ICollection<tblhareketler> tblhareketler { get; set; }
    }
}
