//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCKutuphane.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblyazarlar
    {
        public tblyazarlar()
        {
            this.tblkitaplar = new HashSet<tblkitaplar>();
        }
    
        public int ID { get; set; }
        [Required(ErrorMessage ="Adý boþ geçemezsiniz.")]
        public string AD { get; set; }
        public string SOYAD { get; set; }
        public string DETAY { get; set; }
    
        public virtual ICollection<tblkitaplar> tblkitaplar { get; set; }
    }
}
